apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: workflows-template
  source:
    directory:
      recurse: true
      jsonnet: {}
    repoURL: https://github.com/damienjacinto/demo-workflows
    path: "workflows"
  syncPolicy:
    automated:
      prune: true
