apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: workflows-template
  source:
    directory:
      recurse: true
    repoURL: https://github.com/damienjacinto/demo-workflows
    targetRevision: main
    path: "."
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
