apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slack-events
  namespace: argocd
spec:
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  project: argo-events
  source:
    directory:
      recurse: true
      jsonnet: {}
    repoURL: https://github.com/damienjacinto/demo-argo-events
    path: "slack"
  syncPolicy:
    automated:
      prune: true
